#!/bin/bash 

#### Defense finder #######################

conda create –name defensefinder
conda activate defensefinder
pip install mdmparis-defense-finder
# pip install -U mdmparis-defense-finder
defense-finder update
defense-finder update --help

#################Antfagines sistemos #############3

### Suskaidymas i kelis failus, kadangi su 263 sekomis per didelis.

cat visos.faa | head -130 > pirma_puse.faa

 sed -n '131,260p' visos.faa > antra_dalis.faa
 sed -n '261,410p' visos.faa > trecia_dalis.faa
sed -n '410,540p' visos.faa > ketvirta_dalis.faa

#Rezultatais naujoje output direktorijose
defensefinder run ../pirma_puse.faa
defensefinder run ../antra_dalis.faa
defensefinder run ../trecia_dalis.faa
defensefinder run ../ketvirta_dalis.faa


# vienas failas

cat output_1/pirma_puse_defense_finder_systems.tsv output_2/antra_puse_defense_finder_systems.tsv output_3/trecia_puse_defense_finder_systems.tsv output_4/ketvirta_dalis_defense_finder_systems.tsv >> apsaugines_sistemos.tsv

 mv ../../../PROGRAMOS/defense-finder/apsaugines_sistemos.tsv .