#!/bin/bash 
git add .
git commit -m profagai
git push -u origin master
git push


#Bandymas su PhasTest_API

sudo apt-get update && sudo apt-get install jq -y
git clone https://github.com/ansontwk/PhasTest_API.git
cd PhasTest_API
chmod +x Phastest_API.sh

 cat ../../../defense-finder/pirma_puse.faa > I_dalis.fna
cat ../../../defense-finder/antra_dalis.faa > II_dalis.fna
cat ../../../defense-finder/trecia_dalis.faa > III_dalis.fna
cat ../../../defense-finder/ketvirta_dalis.faa > IV_dalis.fna


#### Submitting job


# bash phastest_api.sh --submitjob --inputDir ./00.fnafiles

# bash phastest_api.sh --getresults --outDir ./output phastest_results

# bash phastest_api.sh --getresults --outDir ./01.phastest_results --cleanup


################ Rezultatu reikia laukti per ilgai



## SU DOCKER again

docker pull wishartlab/phastest-docker
